### ISSUE TITLE
File not been written on remote server

### ISSUE THREAD

**Issue by ghost** [Agence-DnD/DnD-MagentoConnectorBundle#20]
Hi there,
I am having issues getting the file written on the remote server. I have confirmed that the connection is fine by changing the credentials in the export profile which results in the expected error.
However no matter what I put in the remote filepath I am not getting anything. In some cases I am getting an error message like:

CATEGORIES EXPORT  Could not open file

which is expected if the filepath was incorrect (but the message would be better to say 'Could not create file' to avoid confusion). However, the filepath is correct and owned by the ssh user with full permssions (777). 

Othertimes I am getting "Completed" (no errors) but the file is not present.

**Comment by ghost** [comment]
seems it is working now.

**Comment by amitvkhajanchi** [comment]
Hello:

I am having the same issue?  I am not sure how to troubleshoot this?  The export runs without a hitch but I cannot find the file in the remote server?  Thru command line I checked if sftp was working properly and it was.  However, when I connect via command line the sftp client as that the remote server cannot be authenticated and asks if I want to proceed (y/n).  Then I type in password and a key gets generated.

I can do all of this as owner user of /home/akeneo directory.  However the php process uses 'nobody' user (apache user in CentOS system).  Is this caused because of this?
