### ISSUE TITLE
Attributes CSV file is not upload to FTP server

### ISSUE THREAD

**Issue by johnny1991** [Agence-DnD/DnD-MagentoConnectorBundle#6]
Hi, 

In my export attribute profil, if set '/tmp/export_%datetime%.csv ' in file path, my CSV file is not uploaded to FTP server.

The name of my path contains spaces (ex : "/tmp/export_2015-04-17 17:58:04.csv")
and in this file vendor/agencednd/magento-connector-bundle/DnD/Bundle/MagentoConnectorBundle/Writer/File/CsvWriter.php at line 269, PHP return FALSE with file_exists() function because filePath contains spaces. 

I propose the following solution : 

``` php
 if(file_exists($this->getPath())){
      $sftpConnection->uploadFile($this->getPath(), $this->getRemoteFilePath());
 }
```

I am trying to implement the FTP connection, if that interests you ...

Regards
Johnny1991

**Comment by DnD-Mimosa** [comment]
Hi Johnny,

As it was said in the README, FTP export is not already implemented and it will be available in a futur release, that's why you CSV file is not upload to FTP server.

Thank you for the solution that you propose, we'll certainly insert it in our Bundle.

If you want to implement FTP connection, don't hesitate to do a pull request on our github.

Regards,
Florian.
